services:
  - type: web
    name: booking-app
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booking-db
          property: connectionString

databases:
  - name: booking-db
    plan: free